group "com.jbferreira.launchappstore"

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    namespace = "com.jbferreira.launchappstore"
    compileSdk = 34

    defaultConfig {
        minSdkVersion = 19
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }
}
